imports:
    - { resource: "services_legacy.yml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Service\YamlLoader:
        arguments:
            - "%kernel.root_dir%"

    AppBundle\Service\Cloudflare:
        arguments:
            - "@csa_guzzle.client.cloudflare"
            - "@logger"
            - "%cloudflare_api_mawaqit_id%"
            - "%site%"
            - "%languages%"

    AppBundle\Service\Statistic:
        arguments:
            - "@csa_guzzle.client.elastic"
            - "@logger"

    AppBundle\EventListener\CommentListener:
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\MosqueElasticListener:
        arguments:
            - "@app.mosque_service"
            - "@doctrine.orm.entity_manager"
            - "@app.request_service"
        tags:
            - { name: 'doctrine.event_subscriber' }

    AppBundle\EventListener\MosqueCacheListener:
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }